commands:
  - /god
cooldowns:
  /god: 60

group: premium

url: jdbc:mysql://localhost:3306/test
username: test
password: test

coloumns:
  - amountCase1
  - amountCase2
  - amountCase3

permissions:
  - ultracosmetics.gadgets.batblaster
  - ultracosmetics.gadgets.chickenator
  - ultracosmetics.gadgets.colorbomb
  - ultracosmetics.gadgets.discoball
  - ultracosmetics.gadgets.etherealpearl
  - ultracosmetics.gadgets.fleshhook
  - ultracosmetics.gadgets.melonthrower
  - ultracosmetics.gadgets.blizzardblaster
  - ultracosmetics.gadgets.portalgun
  - ultracosmetics.gadgets.explosivesheep
  - ultracosmetics.gadgets.paintballgun
  - ultracosmetics.gadgets.thorhammer
  - ultracosmetics.gadgets.antigravity
  - ultracosmetics.gadgets.smashdown